### PR TITLE
MSVC fixes

### PR DESCRIPTION
**Pull request by ukoethe**
First set of MSVC fixes. Remaining problems:
- Initializer lists are unsupported by Visual Studio 2012 (the current ilastik compiler on Windows). You must remove all of them. Here is a not necessarily complete list: `featurestore.cpp` line 75, `higher_order_features.cpp` lines 217, 218, 224, `tracking.cpp` line 959
- `IsCompleteType<T>` does not compile if `T` is an incomplete type.
- `MoveEnergy::operator ()` is most certainly wrong -- I added `assert(false)` to make sure that this is never executed. Please check what the function was supposed to do and correct. Note that `std::inner_product` is unsupported on Visual Studio 2012.
- `constrackinginferencemodel.cpp`, line 343: `>` is undefined for bool
- `hypotheses.cpp`, line 69:

```
 binary '=' : no operator found which takes a right-hand operand of
 type 'std::vector<_Ty>' (or there is no acceptable conversion)
          with 
              _Ty=size_t
          and
              _Ty=unsigned long
```

I didn't get far enough to check for missing `PGMLINK_EXPORT`. 

I've seen many functions that take 10 or more parameters (up to maybe 20). This is **extremely bad design**.

### CODE REVIEW

**Comment by ilastikdev** [comment]
"IsCompleteType<T> does not compile..." on MS VS 2012; it  is from opengm.

Pull learning-experimental from
https://github.com/ilastikdev/opengm-1

**Comment by chaubold** [comment]
Could you please make a pull request with the required changes to OpenGM's learning-experimental branch so everyone can use the fix? Thanks

**Comment by ilastikdev** [comment]
The latest commit compiles on gcc and clang, but has not been tested on windows yet,
hence no pull request yet.

**Comment by ilastikdev** [comment]
ready to be merged into pgmlink/master

**Comment by chaubold** [comment]
Looks good, thanks a lot!

**Pull request merged**
